name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/exporter:latest .
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/exporter:latest
      - name: Push Docker image with tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tag=${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/${{ github.repository }}/exporter:latest ghcr.io/${{ github.repository }}/exporter:$tag
          docker push ghcr.io/${{ github.repository }}/exporter:$tag